spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service:
  greeting: "Pronto-dev"
  default-value: "Estou-dev"